SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS notifikasi;
DROP TABLE IF EXISTS resep_obat;
DROP TABLE IF EXISTS rekam_medis;
DROP TABLE IF EXISTS booking_antrean;
DROP TABLE IF EXISTS dokter;
DROP TABLE IF EXISTS poliklinik;
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS pasien;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE pasien (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nik VARCHAR(32) NOT NULL UNIQUE,
  nama VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  no_telp VARCHAR(32) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE admin (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE poliklinik (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama_poli VARCHAR(120) NOT NULL,
  deskripsi TEXT NOT NULL,
  kapasitas INT NOT NULL DEFAULT 20,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE dokter (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_poli INT NULL,
  nama VARCHAR(120) NOT NULL,
  spesialisasi VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  no_telp VARCHAR(32) NOT NULL,
  jadwal_praktik VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_dokter_poliklinik
    FOREIGN KEY (id_poli) REFERENCES poliklinik(id)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE booking_antrean (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_pasien INT NOT NULL,
  id_dokter INT NOT NULL,
  tanggal_kunjungan DATE NOT NULL,
  jam_slot TIME NOT NULL,
  nomor_antrean INT NOT NULL,
  status_booking ENUM('Pending', 'Done', 'Cancelled') NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_booking_dokter_tanggal (id_dokter, tanggal_kunjungan),
  INDEX idx_booking_pasien (id_pasien),
  CONSTRAINT fk_booking_pasien
    FOREIGN KEY (id_pasien) REFERENCES pasien(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_booking_dokter
    FOREIGN KEY (id_dokter) REFERENCES dokter(id)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE rekam_medis (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_booking INT NOT NULL UNIQUE,
  id_pasien INT NOT NULL,
  id_dokter INT NOT NULL,
  keluhan TEXT NOT NULL,
  diagnosa TEXT NOT NULL,
  catatan_dokter TEXT NOT NULL,
  tanggal_periksa DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_rekam_pasien (id_pasien),
  INDEX idx_rekam_dokter (id_dokter),
  CONSTRAINT fk_rekam_booking
    FOREIGN KEY (id_booking) REFERENCES booking_antrean(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_rekam_pasien
    FOREIGN KEY (id_pasien) REFERENCES pasien(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_rekam_dokter
    FOREIGN KEY (id_dokter) REFERENCES dokter(id)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE resep_obat (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_rekam_medis INT NOT NULL,
  detail_obat TEXT NOT NULL,
  dosis VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_resep_rekam_medis
    FOREIGN KEY (id_rekam_medis) REFERENCES rekam_medis(id)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE notifikasi (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_pasien INT NOT NULL,
  id_booking INT NULL,
  jenis ENUM('booking_created', 'booking_cancelled', 'booking_done', 'rekam_medis') NOT NULL,
  judul VARCHAR(160) NOT NULL,
  pesan TEXT NOT NULL,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_notif_pasien (id_pasien, is_read),
  CONSTRAINT fk_notif_pasien
    FOREIGN KEY (id_pasien) REFERENCES pasien(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_notif_booking
    FOREIGN KEY (id_booking) REFERENCES booking_antrean(id)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
